# Generated by Django 5.0.6 on 2024-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_statstics_end_year_alter_statstics_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statstics',
            name='added',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statstics',
            name='published',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statstics',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
