# Generated by Django 5.0.6 on 2024-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_statstics_country_alter_statstics_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statstics',
            name='insight',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='statstics',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='statstics',
            name='topic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
